# Use Node.js official image as base image
FROM node:16

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files from the backend directory into the container
COPY . .

# Expose the port the app will run on
EXPOSE 3000

# Set environment variables for production
ENV NODE_ENV=production

# Start the backend server
CMD ["npm", "start"]
